"""CAD Intent and Natural Language Command Parser."""
import re
from typing import Optional, Dict, Any
from dataclasses import dataclass, field
from app.cad_engine.commands.units import parse_dimension, parse_angle


@dataclass
class CADPlan:
    """A structured CAD action plan generated by the intent parser."""
    action: str                       # Function name in CADFunctionRegistry, e.g. "CREATE_BOX"
    parameters: dict[str, Any]        # Validated and unit-normalized parameters
    target_query: Optional[str] = None # Pronoun or reference, e.g. "it", "cylinder", "selected"
    requires_target: bool = False
    raw_text: str = ""
    spoken_summary: str = ""
    is_viewport_only: bool = False


class CADIntentParser:
    """Parses natural language and engineering CAD shorthand into executable CADPlans."""

    def parse(self, text: str) -> Optional[CADPlan]:
        raw = text.strip()
        if not raw:
            return None
        lower = raw.lower()

        # ---------------------------------------------------------
        # 1. UNDO / REDO
        # ---------------------------------------------------------
        if re.search(r"\bundo(\s+that|\s+operation|\s+last)?\b", lower):
            return CADPlan(
                action="UNDO",
                parameters={},
                raw_text=raw,
                spoken_summary="Undoing the last operation, sir."
            )
        if re.search(r"\bredo(\s+that|\s+operation)?\b", lower):
            return CADPlan(
                action="REDO",
                parameters={},
                raw_text=raw,
                spoken_summary="Redoing the operation, sir."
            )

        # ---------------------------------------------------------
        # 2. VIEW NAVIGATION & CAMERA
        # ---------------------------------------------------------
        if re.search(r"\b(fit\s+view|fit\s+all|zoom\s+extents|fit\s+objects|frame\s+view)\b", lower):
            return CADPlan(
                action="FIT_VIEW",
                parameters={},
                raw_text=raw,
                is_viewport_only=True,
                spoken_summary="Framing viewport to all objects, sir."
            )

        if re.search(r"\b(toggle\s+section|section\s+view|cutaway\s+view)\b", lower):
            return CADPlan(
                action="SECTION_VIEW",
                parameters={},
                raw_text=raw,
                is_viewport_only=True,
                spoken_summary="Toggling cross-section view, sir."
            )

        # ---------------------------------------------------------
        # 3. MEASURE / DIMENSIONS
        # ---------------------------------------------------------
        if re.search(r"\b(measure|dimensions?|bounding\s*box|volume|surface\s*area)\b", lower):
            target = self._extract_target(lower)
            if "volume" in lower:
                return CADPlan(
                    action="MEASURE_VOLUME",
                    parameters={},
                    target_query=target,
                    requires_target=True,
                    raw_text=raw,
                    spoken_summary="Calculating volume, sir."
                )
            return CADPlan(
                action="MEASURE_BOUNDING_BOX",
                parameters={},
                target_query=target,
                requires_target=True,
                raw_text=raw,
                spoken_summary="Measuring dimensions, sir."
            )

        # ---------------------------------------------------------
        # 4. PATTERNS, ARRAYS & HOLES
        # ---------------------------------------------------------
        circular_pattern_m = (
            re.search(r"\b(?:make|create|drill|array|pattern)\s+(?:a\s+)?(\w+|\d+)?\s*(?:equally\s+spaced\s+)?(?:holes|circular\s+pattern|polar\s+array|circular\s+array|circular)\b", lower)
            or re.search(r"\bcircular\s+pattern\b", lower)
            or re.search(r"\bpolar\s+array\b", lower)
        )
        if circular_pattern_m:
            num_word = circular_pattern_m.group(1) if circular_pattern_m.lastindex else "6"
            num_map = {"two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "eight": 8, "twelve": 12}
            count = num_map.get(str(num_word).lower(), int(num_word) if str(num_word).isdigit() else 6)
            dia_match = re.search(r"(\d+(?:\.\d+)?)\s*(?:mm)?\s*(?:dia|diameter|size)", lower)
            dia = float(dia_match.group(1)) if dia_match else 5.0
            return CADPlan(
                action="PATTERN_CIRCULAR",
                parameters={"count": count, "angle": 360.0, "radius": 25.0, "hole_diameter": dia},
                target_query=self._extract_target(lower),
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Creating circular pattern with {count} instances, sir."
            )

        linear_pattern_m = (
            re.search(r"\b(?:linear\s+pattern|linear\s+array|rectangular\s+array)\b", lower)
            or re.search(r"\b(?:make|create)\s+(\w+|\d+)\s+linear\s+pattern\b", lower)
        )
        if linear_pattern_m:
            num_word = linear_pattern_m.group(1) if linear_pattern_m.lastindex else "3"
            num_map = {"two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "eight": 8}
            count = num_map.get(str(num_word).lower(), int(num_word) if str(num_word).isdigit() else 3)
            spacing_m = re.search(r"spacing\s*=?\s*(\d+(?:\.\d+)?)", lower)
            spacing = float(spacing_m.group(1)) if spacing_m else 30.0
            return CADPlan(
                action="PATTERN_LINEAR",
                parameters={"count_x": count, "count_y": 1, "spacing_x": spacing, "spacing_y": 0.0},
                target_query=self._extract_target(lower),
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Creating linear pattern with {count} instances, sir."
            )

        if re.search(r"\bmirror\b", lower):
            plane = "YZ" if "yz" in lower else ("XY" if "xy" in lower else "XZ")
            return CADPlan(
                action="MIRROR",
                parameters={"plane": plane},
                target_query=self._extract_target(lower),
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Mirroring object across {plane} plane, sir."
            )

        if re.search(r"\b(?:boolean\s+union|union)\b", lower):
            return CADPlan(
                action="BOOLEAN_UNION",
                parameters={},
                requires_target=False,
                raw_text=raw,
                spoken_summary="Executing Boolean Union on objects, sir."
            )

        if re.search(r"\b(?:boolean\s+cut|boolean\s+subtract|subtract\s+solid)\b", lower):
            return CADPlan(
                action="BOOLEAN_CUT",
                parameters={},
                requires_target=False,
                raw_text=raw,
                spoken_summary="Executing Boolean Cut subtraction, sir."
            )

        if re.search(r"\b(?:boolean\s+intersect|intersection)\b", lower):
            return CADPlan(
                action="BOOLEAN_INTERSECT",
                parameters={},
                requires_target=False,
                raw_text=raw,
                spoken_summary="Executing Boolean Intersection, sir."
            )

        if re.search(r"\bextrude\b", lower):
            dist_m = re.search(r"(\d+(?:\.\d+)?)\s*(?:mm)?", lower)
            dist = float(dist_m.group(1)) if dist_m else 25.0
            return CADPlan(
                action="EXTRUDE",
                parameters={"distance": dist},
                requires_target=False,
                raw_text=raw,
                spoken_summary=f"Extruding profile by {dist:g} mm, sir."
            )

        if re.search(r"\brevolve\b", lower):
            ang_m = re.search(r"(\d+(?:\.\d+)?)\s*(?:deg|degrees)?", lower)
            ang = float(ang_m.group(1)) if ang_m else 360.0
            return CADPlan(
                action="REVOLVE",
                parameters={"angle": ang},
                requires_target=False,
                raw_text=raw,
                spoken_summary=f"Revolving profile by {ang:g} degrees, sir."
            )

        hole_match = re.search(r"\b(make|drill|add|create|cut)\s+(?:a\s+)?(\d+(?:\.\d+)?)\s*(?:mm|inch|in)?\s*hole\b", lower)
        if hole_match or ("hole" in lower and re.search(r"\b(\d+(?:\.\d+)?)\s*(?:mm)?\b", lower)):
            dia_m = re.search(r"(\d+(?:\.\d+)?)\s*(?:mm|inch|in)?\s*hole", lower) or re.search(r"hole\s+(?:of\s+)?(\d+(?:\.\d+)?)", lower)
            dia = float(dia_m.group(1)) if dia_m else 10.0
            depth_m = re.search(r"(?:depth|deep)\s*(?:of\s+)?(\d+(?:\.\d+)?)", lower)
            depth = float(depth_m.group(1)) if depth_m else None
            
            # Position at center or coords
            x, y = 0.0, 0.0
            coord_m = re.search(r"\bat\s*\(?(-?\d+(?:\.\d+)?)[,\s]+(-?\d+(?:\.\d+)?)\)?", lower)
            if coord_m:
                x, y = float(coord_m.group(1)), float(coord_m.group(2))

            return CADPlan(
                action="CREATE_HOLE",
                parameters={"diameter": dia, "depth": depth, "x": x, "y": y},
                target_query=self._extract_target(lower),
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Creating a {dia:g} mm hole{' at the center' if x == 0 and y == 0 else f' at ({x}, {y})'}, sir."
            )

        # ---------------------------------------------------------
        # 5. PARAMETRIC UPDATES ("Change the radius to 25 mm", "Make its height 100 mm")
        # ---------------------------------------------------------
        param_change_m = re.search(
            r"\b(?:change|make|set|adjust|update)\b[^.;]*?\b(?:its|the|that)?\s*(height|width|depth|radius|diameter|thickness)\s*(?:to|=|:)?\s*(\d+(?:\.\d+)?(?:\s*/\s*\d+)?)\s*([a-z\"']*)",
            lower
        )
        if param_change_m:
            param_key = param_change_m.group(1)
            raw_val = param_change_m.group(2)
            unit_str = param_change_m.group(3) or "mm"
            val_mm, _ = parse_dimension(f"{raw_val} {unit_str}")
            
            if param_key == "diameter":
                param_key = "radius"
                val_mm = val_mm / 2.0

            target = self._extract_target(lower)
            return CADPlan(
                action="UPDATE_PARAMETERS",
                parameters={"parameters": {param_key: val_mm}},
                target_query=target,
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Updating {param_key} to {val_mm:g} mm and regenerating geometry, sir."
            )

        # ---------------------------------------------------------
        # 6. TRANSFORMATIONS ("Rotate the selected part 45 degrees", "Move that cylinder 50 mm on X")
        # ---------------------------------------------------------
        if "rotate" in lower:
            deg_m = re.search(r"(-?\d+(?:\.\d+)?)\s*(?:deg|degrees?|°)?", lower)
            deg = float(deg_m.group(1)) if deg_m else 45.0
            axis = "x" if re.search(r"\b(?:about|around|on|to)?\s*(?:the\s*)?x\b", lower) else \
                   "z" if re.search(r"\b(?:about|around|on|to)?\s*(?:the\s*)?z\b", lower) else "y"
            target = self._extract_target(lower)
            return CADPlan(
                action="TRANSFORM_ROTATE",
                parameters={"angle": deg, "axis": axis},
                target_query=target,
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Rotating {target or 'selected part'} {deg:g} degrees about {axis.upper()}, sir."
            )

        if "move" in lower:
            axis_m = re.search(r"\b([xyz])\b\s*(?:to|=|:|at)?\s*(-?\d+(?:\.\d+)?)", lower)
            offset_m = re.search(r"(-?\d+(?:\.\d+)?)\s*(?:mm)?\s*(?:on|along|in)?\s*([xyz])\b", lower)
            dir_right_m = re.search(r"(-?\d+(?:\.\d+)?)\s*(?:mm)?\s*(?:to\s+the\s+)?(right|left|up|down|forward|backward)", lower)
            
            x, y, z = 0.0, 0.0, 0.0
            if axis_m:
                ax, val = axis_m.group(1), float(axis_m.group(2))
                if ax == 'x': x = val
                elif ax == 'y': y = val
                elif ax == 'z': z = val
            elif offset_m:
                val, ax = float(offset_m.group(1)), offset_m.group(2)
                if ax == 'x': x = val
                elif ax == 'y': y = val
                elif ax == 'z': z = val
            elif dir_right_m:
                val, direction = float(dir_right_m.group(1)), dir_right_m.group(2)
                if direction == "right": x = val
                elif direction == "left": x = -val
                elif direction == "up": y = val
                elif direction == "down": y = -val
                elif direction == "forward": z = val
                elif direction == "backward": z = -val

            target = self._extract_target(lower)
            return CADPlan(
                action="TRANSFORM_MOVE",
                parameters={"x": x, "y": y, "z": z},
                target_query=target,
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Moving {target or 'object'} by {x or y or z:g} mm, sir."
            )

        # ---------------------------------------------------------
        # 7. FILLET / CHAMFER / SHELL
        # ---------------------------------------------------------
        if "fillet" in lower or "round" in lower:
            r_m = re.search(r"(\d+(?:\.\d+)?)\s*(?:mm)?", lower)
            r = float(r_m.group(1)) if r_m else 3.0
            return CADPlan(
                action="FILLET",
                parameters={"radius": r},
                target_query=self._extract_target(lower),
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Applying {r:g} mm fillet, sir."
            )

        if "chamfer" in lower or "bevel" in lower:
            d_m = re.search(r"(\d+(?:\.\d+)?)\s*(?:mm)?", lower)
            d = float(d_m.group(1)) if d_m else 2.0
            return CADPlan(
                action="CHAMFER",
                parameters={"distance": d},
                target_query=self._extract_target(lower),
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Applying {d:g} mm chamfer, sir."
            )

        if "shell" in lower or "hollow" in lower:
            t_m = re.search(r"(\d+(?:\.\d+)?)\s*(?:mm)?", lower)
            t = float(t_m.group(1)) if t_m else 2.0
            return CADPlan(
                action="SHELL",
                parameters={"thickness": t},
                target_query=self._extract_target(lower),
                requires_target=True,
                raw_text=raw,
                spoken_summary=f"Shelling solid with {t:g} mm wall thickness, sir."
            )

        # ---------------------------------------------------------
        # 8. 3D PRIMITIVE CREATION ("Create a box 100 by 60 by 20 mm", "box 100 60 20")
        # ---------------------------------------------------------
        if re.search(r"\b(box|cube|rectangular\s+prism)\b", lower):
            # Check "100 by 60 by 20" or "100x60x20" or "100 60 20"
            dims_3d = re.findall(r"(\d+(?:\.\d+)?)\s*(?:by|x|\*|\s+)\s*(\d+(?:\.\d+)?)\s*(?:by|x|\*|\s+)\s*(\d+(?:\.\d+)?)", lower)
            if dims_3d:
                w, h, d = float(dims_3d[0][0]), float(dims_3d[0][1]), float(dims_3d[0][2])
            else:
                w_m = re.search(r"(?:width|w)\s*=?\s*(\d+(?:\.\d+)?)", lower)
                h_m = re.search(r"(?:height|h)\s*=?\s*(\d+(?:\.\d+)?)", lower)
                d_m = re.search(r"(?:depth|d|length|l)\s*=?\s*(\d+(?:\.\d+)?)", lower)
                w = float(w_m.group(1)) if w_m else 100.0
                h = float(h_m.group(1)) if h_m else 50.0
                d = float(d_m.group(1)) if d_m else 20.0
            
            return CADPlan(
                action="CREATE_BOX",
                parameters={"width": w, "height": h, "depth": d, "name": "Box"},
                raw_text=raw,
                spoken_summary=f"Creating a box {w:g} by {h:g} by {d:g} mm, sir."
            )

        if re.search(r"\b(cylinder|tube|pipe)\b", lower):
            r_m = re.search(r"(?:radius|r)\s*=?\s*(\d+(?:\.\d+)?)", lower)
            dia_m = re.search(r"(?:diameter|dia|d)\s*=?\s*(\d+(?:\.\d+)?)", lower)
            h_m = re.search(r"(?:height|h|length|l)\s*=?\s*(\d+(?:\.\d+)?)", lower)
            
            r = float(r_m.group(1)) if r_m else (float(dia_m.group(1)) / 2.0 if dia_m else 20.0)
            h = float(h_m.group(1)) if h_m else 60.0

            return CADPlan(
                action="CREATE_CYLINDER",
                parameters={"radius": r, "height": h, "name": "Cylinder"},
                raw_text=raw,
                spoken_summary=f"Creating a cylinder with radius {r:g} mm and height {h:g} mm, sir."
            )

        if re.search(r"\b(sphere|ball)\b", lower):
            r_m = re.search(r"(?:radius|r)\s*=?\s*(\d+(?:\.\d+)?)", lower)
            dia_m = re.search(r"(?:diameter|dia|d)\s*=?\s*(\d+(?:\.\d+)?)", lower)
            r = float(r_m.group(1)) if r_m else (float(dia_m.group(1)) / 2.0 if dia_m else 25.0)

            return CADPlan(
                action="CREATE_SPHERE",
                parameters={"radius": r, "name": "Sphere"},
                raw_text=raw,
                spoken_summary=f"Creating a sphere with radius {r:g} mm, sir."
            )

        if re.search(r"\b(cone)\b", lower):
            r_m = re.search(r"(?:radius|r)\s*=?\s*(\d+(?:\.\d+)?)", lower)
            h_m = re.search(r"(?:height|h)\s*=?\s*(\d+(?:\.\d+)?)", lower)
            r = float(r_m.group(1)) if r_m else 20.0
            h = float(h_m.group(1)) if h_m else 40.0
            return CADPlan(
                action="CREATE_CONE",
                parameters={"radius": r, "height": h, "name": "Cone"},
                raw_text=raw,
                spoken_summary=f"Creating a cone with radius {r:g} mm and height {h:g} mm, sir."
            )

        # ---------------------------------------------------------
        # 9. DELETE / REMOVE
        # ---------------------------------------------------------
        if re.search(r"\b(delete|erase|remove)\b", lower):
            target = self._extract_target(lower)
            return CADPlan(
                action="DELETE_FEATURE",
                parameters={},
                target_query=target,
                requires_target=True,
                raw_text=raw,
                spoken_summary="Deleting selected object, sir."
            )

        return None

    def _extract_target(self, text: str) -> Optional[str]:
        """Extract object reference or pronoun from command string."""
        if re.search(r"\b(it|its|that|this)\b", text):
            return "it"
        if "selected" in text or "current" in text:
            return "selected"
        for t in ["cylinder", "box", "sphere", "cone", "torus", "sketch", "hole", "extrusion"]:
            if t in text:
                return t
        return None


_global_intent_parser = CADIntentParser()


def get_intent_parser() -> CADIntentParser:
    return _global_intent_parser
